2025-07-16 19:35:52,282 - INFO: ================================================================================
2025-07-16 19:35:52,283 - INFO: URL: https://polymarket.com/event/which-company-has-best-ai-model-end-of-august | interval=max fidelity=1 trades=False book=False
2025-07-16 19:35:52,284 - INFO: ================================================================================
2025-07-16 19:35:53,590 - INFO: Market 1 / 12
2025-07-16 19:35:53,598 - INFO: • Will Google have the top AI model on August 31?
2025-07-16 19:35:55,066 - INFO:   ✓ saved which-company-has-best-ai-model-end-of-august-will-google-have-the-top-ai-model-on-august-31-enriched.csv (2220 rows)
2025-07-16 19:35:55,077 - INFO: Market 2 / 12
2025-07-16 19:35:55,077 - INFO: • Will another company have the top AI model on August 31?
2025-07-16 19:35:55,837 - ERROR: Fatal error: Length mismatch: Expected axis has 0 elements, new values have 2 elements
Traceback (most recent call last):
  File "C:\Users\User\python_code\poly_market\using_clob_api.py", line 285, in main
    write_csv(slug, m, interval, fidelity, want_tr, want_book)
  File "C:\Users\User\python_code\poly_market\using_clob_api.py", line 213, in write_csv
    df = market_prices(market, interval, fidelity)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\python_code\poly_market\using_clob_api.py", line 112, in market_prices
    df.columns = ["price_yes", "price_no"]
    ^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 2 elements
2025-07-16 19:35:56,027 - INFO: Done.  Log → logs\poly_20250716_193552.log

